### ISSUE TITLE
upgrade tensflow logo and app name

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/helm-charts#11]
Use this image https://github.com/gurvindersingh/deep-learning as it contains most of DL frameworks.

Upgrade the dockerfile to have the env variable for versions of relevant packages e.g. tensorflow, pytorch etc. and add those as tags to helm chart so users know which version of packages are installed in this version of helm chart.

**Comment by paalka** [comment]
Closing, as b4157b73514dadbff7635c10373960a9e41113f8 adds a chart that uses a variant of the mentioned image.

**Comment by gurvindersingh** [comment]
We should have PVC support for this one. Reopening the issue

**Comment by paalka** [comment]
PVC support has now been added in version 0.1.1

**Comment by gurvindersingh** [comment]
Yup :)
