### ISSUE TITLE
Ensure the API versions are up-to-date

### ISSUE THREAD

**Issue by paalka** [Uninett/helm-charts#13]
Currently we are for instance using extensions/v1betav1, we should probably use what is in the most recent version, as this will ensure future compatiability

**Comment by gurvindersingh** [comment]
I think we can take this one later as well. as currently we have not moved to 1.10 which means we can wait a bit and before opening up to end user we will move to apps/v1.

**Comment by paalka** [comment]
This is now fixed in all charts in the testing repo.

**Comment by paalka** [comment]
Closing, as the stable charts are now up-to-date.
