### ISSUE TITLE
Add detailed instructions on how to submit a chart

### ISSUE THREAD

**Issue by paalka** [Uninett/helm-charts#6]
It might be useful to create a tutorial which goes through the whole process of creating a Docker image, constructing a chart, and submitting it, as this will make it significantly easier for other users to submit chart.

It could also be useful to create utilities for testing the chart, ex. a visualization of what the deployment will look like or provide instructions on how to test the chart on a test cluster.

**Comment by gurvindersingh** [comment]
update it based on testing and stable setup

**Comment by paalka** [comment]
This has been added.
