### ISSUE TITLE
groups information not asked

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/helm-charts#9]
When you add authorization based on groups to be allowed to access e.g. notebook server. Upon accessing the server, proxy does not send the group scope to dataporten which means a user can not get access to the notebook server even though he/she is member of that group. Looking at the [code](https://github.com/UNINETT/goidc-proxy/blob/93bdd9f68ad3c1fb33a017c2c0a896c13a082c9b/oidc.go#L51) , scope needs to be passed comma separated strings not as array as passed currently [scope1 scope2 scope3].

This needs to be fixed to all the charts which uses goidc-proxy

**Comment by paalka** [comment]
029facd499d7333afe451895fe692ab40cd7088d should fix this for all charts that use goidc-proxy

**Comment by gurvindersingh** [comment]
tested and its working.
